version = 0.1

[default.global.parameters]
stack_name = "audio-watermark"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true   # auto-create/manage the ECR repo for the container image
